export const PERMISSIONS = {
  VIEW_DASHBOARD: "view_dashboard",
  MANAGE_USERS: "manage_users",
  MANAGE_TEAMS: "manage_teams",
  MANAGE_PROJECTS: "manage_projects",
  ASSIGN_TASKS: "assign_tasks",
  TEST_TASKS: "test_tasks",
  VIEW_REPORTS: "view_reports",
  MANAGE_SETTINGS: "manage_settings",
  MANAGE_ROLES: "manage_roles",
};

export const ROLE_PERMISSIONS = {
  SUPER_ADMIN: ["*"],
  ADMIN: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.MANAGE_USERS,
    PERMISSIONS.MANAGE_PROJECTS,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.MANAGE_SETTINGS,
  ],
  PROJECT_MANAGER: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.MANAGE_TEAMS,
    PERMISSIONS.ASSIGN_TASKS,
    PERMISSIONS.VIEW_REPORTS,
  ],
  QA_TESTER: [PERMISSIONS.VIEW_DASHBOARD, PERMISSIONS.TEST_TASKS],
  TEAM_MEMBER: [PERMISSIONS.VIEW_DASHBOARD],
};

export const ROLE_DEFAULT_PERMISSIONS = {
  PROJECT_MANAGER: [
    PERMISSIONS.MANAGE_TEAMS,
    PERMISSIONS.MANAGE_PROJECTS,
  ],
};

export const SENSITIVE_PERMISSIONS = [
  PERMISSIONS.MANAGE_ROLES,
];
